seed: 1
gamma: 0.99
rl_test_episodes: 100000
batch_size: 64
eps_start: 1.0
eps_end: 0.02
target_update: 1000
lr: 0.0001
initial_memory: 1000
save_model_episode: 10
record_episode: 10
hidden_size: 256
cumulants: 64
update_every: 4
irl_steps: 1
n_episodes: 10000
eps_decay: 20000
retraining_tasks: 10 
n_actions: 5
# training-specific 
version: "default"
demonstrations: 300